apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: phoenix-app-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: phoenix-app
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics